basePath: /
definitions:
  gosimplecms_controllers_admin_posts_list.Post:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      slug:
        type: string
      status:
        type: string
    type: object
  gosimplecms_controllers_posts_list.Post:
    properties:
      created_at:
        type: string
      id:
        type: integer
      published_at:
        type: string
      slug:
        type: string
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  models.CreateCategoryRequest:
    properties:
      name:
        type: string
      slug:
        type: string
    type: object
  models.CreatePostRequest:
    properties:
      category_ids:
        items:
          type: integer
        type: array
      content:
        type: string
      slug:
        type: string
      tag_ids:
        items:
          type: integer
        type: array
      title:
        type: string
      user_id:
        type: integer
    type: object
  models.CreateTagRequest:
    properties:
      name:
        type: string
      slug:
        type: string
    type: object
  models.CreateUpdateCategoryResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      slug:
        type: string
    type: object
  models.CreateUpdatePostResponse:
    properties:
      created_at:
        type: string
      current_version_number:
        type: integer
      id:
        type: integer
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  models.CreateUpdateTagResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      slug:
        type: string
    type: object
  models.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.LoginResponse:
    properties:
      token:
        type: string
    type: object
  models.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  models.RegisterResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      role:
        type: string
    type: object
  models.TagRelationship:
    properties:
      coOccurrenceCount:
        type: integer
      score:
        type: number
      tag1ID:
        type: integer
      tag2ID:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a simple API with JWT Auth, RBAC, and Clean Architecture.
  title: Go Simple CMS API
  version: "1.0"
paths:
  /api/v1/admin/categories:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CreateUpdateCategoryResponse'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all categories
      tags:
      - Manage Categories
    post:
      consumes:
      - application/json
      description: Create a new category
      parameters:
      - description: Category data
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/models.CreateCategoryRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.CreateUpdateCategoryResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new category
      tags:
      - Manage Categories
  /api/v1/admin/posts:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/gosimplecms_controllers_admin_posts_list.Post'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all posts
      tags:
      - Manage Posts
    post:
      consumes:
      - application/json
      description: Create a new post
      parameters:
      - description: Post data
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/models.CreatePostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.CreateUpdatePostResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new post
      tags:
      - Manage Posts
  /api/v1/admin/posts/{id}:
    put:
      consumes:
      - application/json
      description: Update existing post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      - description: Post data
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/models.CreatePostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.CreateUpdatePostResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update existing post
      tags:
      - Manage Posts
  /api/v1/admin/posts/{id}/publish:
    put:
      consumes:
      - application/json
      description: Publish existing post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CreateUpdatePostResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Publish existing post
      tags:
      - Manage Posts
  /api/v1/admin/tags:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CreateUpdateCategoryResponse'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all tags
      tags:
      - Manage Tags
    post:
      consumes:
      - application/json
      description: Create a new tag
      parameters:
      - description: Tag data
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/models.CreateTagRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.CreateUpdateTagResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new tag
      tags:
      - Manage Tags
  /api/v1/posts:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/gosimplecms_controllers_posts_list.Post'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all posts
      tags:
      - Posts
  /api/v1/posts/{id}:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CreateUpdatePostResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get detail post
      tags:
      - Posts
  /api/v1/posts/tag-scores:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.TagRelationship'
            type: array
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get tag scores
      tags:
      - Posts
  /api/v1/users/profile:
    get:
      consumes:
      - application/json
      description: Get profile user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.RegisterResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Profile user
      tags:
      - Auth
  /login:
    post:
      consumes:
      - application/json
      description: Create a new users account
      parameters:
      - description: User login
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login users
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Create a new users account
      parameters:
      - description: User registration data
        in: body
        name: users
        required: true
        schema:
          $ref: '#/definitions/models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new users
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
